version: "3"
services:
  coordinator:
    image: nebulastream/nes-executable-image:latest
    entrypoint: ["bash", "-c", "nesCoordinator --configPath=/tutorial/coordinator.yml"]
    ports:
      - 8081:8081
    volumes:
      - ./:/tutorial
    networks:
      elegant-use-case-example-network:
        ipv4_address: 172.31.0.2
  worker:
    image: nebulastream/nes-executable-image:latest
    entrypoint: ["bash", "-c", "sleep 3 && nesWorker --configPath=/tutorial/worker-1.yml"]
    volumes:
      - ./:/tutorial
    networks:
      elegant-use-case-example-network:
        ipv4_address: 172.31.0.3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  accelerationService:
    image: beehivelab/acceleration-service-container:latest
    ports:
      - 8080:8080
    volumes:
      - ./configuration/acceleration_service:/service/files
    networks:
      elegant-use-case-example-network:
        ipv4_address: 172.31.0.4
  plannerService:
    image: ckleitsikas/elegant_planner:latest
    ports:
      - 5000:8081
    networks:
      elegant-use-case-example-network:
        ipv4_address: 172.31.0.5
  verificationService:
    image: beehivelab/code-verification-service-container:latest
    ports:
      - 8082:8080
    volumes:
      - ./configuration/verification_service:/service/files
    networks:
      elegant-use-case-example-network:
        ipv4_address: 172.31.0.6
networks:
  elegant-use-case-example-network:
    ipam:
      config:
        - subnet: 172.31.0.0/24
